home/urls.py
from django.urls import path, re_path
from django.conf import settings
from rest_framework.urlpatterns import format_suffix_patterns
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from . import views


app_name = 'home'

urlpatterns = [
    path('', views.indexView, name='index'),
    #path('', auth_views.login, {'template_name':'home/index.html'}, name='index'),
    path('api-password-token-created/', views.password_reset_token_created, name='api-password-token-created'),
    path('api-login-user/', views.LoginUserView.as_view(), name='api-login-user'),
    path('api-logout-user/', views.LogoutAPIView.as_view(), name='api-logout-user'),
    path('api-user-chat/', views.UserChatAPIView.as_view(), name='api-user-chat'),
    path('api-register-user/', views.create_user, name='api-register-user'),
    path('api-update-user-profile/<int:user__id>/', views.UserProfileUpdateAPIView.as_view(), name='api-update-user-profile'),
    path('api-service-registration/', views.ServiceRegistrationAPIView.as_view(), name='api-service-registration'),
    path('api-service-request/', views.ServiceRequestAPIView.as_view(), name='api-service-request'),
    path('api-service-request-update/<int:pk>/', views.ServiceRequestUpdateView.as_view(), name='api-service-request-update'),
    path('api-get-user-service-request/<int:id>/', views.getuserservicerequest, name='api-get-user-service-request'),
    path('search_results/', views.searchview, name='search_results'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    #path('view-profile/', views.view_profile, name='view-profile'),
    path('profile/', views.view_profile, name='profile'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('service_registration/', views.serviceregistrationview, name='service_registration'),
    path('userdashboard/<int:id>/', views.userdashboard, name='userdashboard'),
    path('sendmessage/<int:id>/', views.sendmessageview, name='sendmessage'),
    path('inbox/', views.inboxview, name='inbox'),
    path('postproject/', views.postprojectview, name='postproject'),
    path('sample_project_display/', views.sampleprojectdisplayview, name='sample_project_display'),
    path('postedsample/<int:id>/', views.SampleServiceDetailView, name='postedsample'),
    path('servicecategory/<slug:slug>/', views.ServiceCategoryView, name='servicecategory'),
    path('service_result_page/<slug:slug>/', views.serviceview, name='service_result_page'),
    path('postedproject/<int:id>/', views.postedprojectview, name='postedproject'),
    path('postprojectlist/', views.postedprojectlist, name='postprojectlist'),
    path('projectbid/', views.projectbidview, name='projectbid'),
    # Rest API from here apart from login at the top
    path('api-service/', views.ServiceView.as_view(), name='api-service'),
    path('api-get-individual-service/<int:id>/', views.individualservice, name='api-get-individual-service'),
    path('api-service-category/', views.ServiceCategoryAPIView.as_view(), name='api-service-category'),
    path('api-service-by-category/<int:id>/', views.service_by_cat, name='api-service-by-category'),
    path('api-vendor-display-by-service/<int:id>/', views.vendordisplay_by_service, name='vendor-display-by-service'),
    path('api-fcm-token-list/', views.FcmUserTokenAPIView.as_view(), name='api-fcm-token-list'),
    path('api-fcm-token-update/<int:pk>/', views.FcmUserTokenUpdateAPIView.as_view(), name='api-fcm-token-update'),
    path('api-send-chat-push-notification/', views.send_chat_message, name='api-send-chat-push-notification'),
    path('api-vendor-sample/', views.VendorSampleView.as_view(), name='api-vendor-sample'),
    #re_path('profile/(?P<pk>[0-9]+)/$', views.EditProfileView.as_view(), name='edit_profile'),
    #path('user-profile/', views.user_profile, name='user_profile'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from home import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.indexView, name='index'),
    path('home/', include('home.urls')),
    path('api/password_reset/', include('django_rest_passwordreset.urls', namespace='password_reset')),
]


admin.site.site_header = "ServApp Administration"
admin.site.site_title = "ServApp Administration Portal"
admin.site.index_title = "Welcome to The ServApp Administration Portal"

home/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from model_utils.models import TimeStampedModel, SoftDeletableModel
from django.template.defaultfilters import date as dj_date
from django.utils.translation import ugettext as _
from django.utils.timezone import localtime
from django.conf import settings
import string
import random


class UserProfile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	slug = models.SlugField(max_length=250,db_index=True)
	first_name = models.CharField(max_length=250, blank=True, null=True)
	last_name = models.CharField(max_length=250, blank=True, null=True)
	phone_number = models.CharField(max_length=250, blank=True, null=True)
	website = models.URLField(default='', blank=True)
	bio = models.TextField(default='', blank=True)
	city = models.CharField(max_length=300, default='', blank=True)
	country = models.CharField(max_length=250, default='', blank=True)
	location_latitude = models.DecimalField(max_digits=20, decimal_places=8, null=True, blank=True)
	location_longitude = models.DecimalField(max_digits=20, decimal_places=8, null=True, blank=True)
	occupation = models.CharField(max_length=300, default='', blank=True)
	organization = models.CharField(max_length=300, default='',blank=True)
	profile_picture = models.ImageField(upload_to='home', blank=True, null=True)

	def __unicode__(self):
		return self.user

def create_profile(sender, **kwargs):
	if kwargs['created']:
		user_profile = UserProfile.objects.create(user=kwargs['instance'])

post_save.connect(create_profile, sender=User)


class FcmUserToken(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	fire_token = models.CharField(max_length=500)

# def create_fcmtoken(sender, **kwargs):
# 	if kwargs['created']:
# 		fcm_usertoken = FcmUserToken.objects.create(user)

class UserLocation(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	region = models.CharField(max_length=250, null=True, blank=True)
	district = models.CharField(max_length=250, null=True, blank=True)
	locality = models.CharField(max_length=250, null=True, blank=True)
	latitude = models.DecimalField(max_digits=20, decimal_places=8, null=True, blank=True)
	longitude = models.DecimalField(max_digits=20, decimal_places=8, null=True, blank=True)
	description = models.CharField(max_length=200, null=True, blank=True)


class ServiceCategory(models.Model):
	name = models.CharField(max_length=250, db_index=True)
	slug = models.SlugField(max_length=250, db_index=True, unique=True)
	image = models.ImageField(blank=True, upload_to='home')

	class Meta:
		ordering = ('name',)
		verbose_name = 'servicecategory'
		verbose_name_plural = 'servicecategories'

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('home:servicecategory', args=[self.slug])

class ServiceProvider(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True)

	def __str__(self):
		return self.user.username
	

class Service(models.Model):
	servicecategory = models.ForeignKey(ServiceCategory, on_delete=models.CASCADE)
	serviceprovider = models.ManyToManyField(ServiceProvider, blank=True)
	date = models.DateTimeField(auto_now_add=True)
	name = models.CharField(max_length=250)
	slug = models.SlugField(max_length=250, db_index=True)
	description = models.TextField()
	sample_image = models.ImageField(blank=True, null=True, upload_to='home')

	def __str__(self):
		return self.name

	class Meta:
		ordering = ('name',)

	

	def get_absolute_url(self):
		return reverse('home:detail', args=[self.id, self.slug])


# New model for service registration. 
class ServiceRegistration(models.Model):
	date_created = models.DateTimeField(auto_now_add=True)
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	servicecategory = models.ForeignKey(ServiceCategory, on_delete=models.CASCADE)
	service = models.ManyToManyField(Service)
	description = models.TextField(null=True, blank=True)

	def __str__(self):
		return self.user.username


#Handle if message is not deliverd, sent a feedback to sender and inlcude staff support contact option
class MessageInbox(models.Model):
	fromUser = models.ForeignKey(User, related_name='fromUser', on_delete=models.CASCADE)
	toUser = models.ForeignKey(User, related_name='toUser', on_delete=models.CASCADE)
	slug = models.SlugField(max_length=250, db_index=True)
	subject = models.CharField(max_length=500)
	message = models.TextField()
	image = models.ImageField(blank=True)
	createdAt = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.subject +'. from '+ self.fromUser.username
#Query for messages -> messages = Message.objects.order_by('fromUser','toUser','createdAt').distinct('fromUser', 'toUser')
#Reverse query -> messages = Message.objects.order_by('fromUser','toUser','-createdAt').distinct('fromUser', 'toUser')


class ServicePackage(models.Model):
	serviceprovider = models.ForeignKey(ServiceProvider, related_name='service_provider', on_delete=models.CASCADE)
	service = models.ForeignKey(Service, related_name='service_package', on_delete=models.CASCADE)
	name = models.CharField(max_length=250)
	description = models.TextField(blank=True)
	delivery_timeline = models.CharField(max_length=100)
	detail = models.TextField(help_text='separate each on a new line')#separate each on a new line
	cost = models.DecimalField(max_digits=10, decimal_places=2)

	def __str__(self):
		return self.name

	def get_detail_list(self):
		return self.detail.split('\n')


#For posting jobs
class PostProject(models.Model):
	client = models.ForeignKey(User, related_name='client', on_delete=models.CASCADE)
	serviceprovider = models.ForeignKey(ServiceProvider, related_name='project_awardee', default='', null=True, on_delete=models.CASCADE)
	#post_date = models.DateTimeField(auto_now_add=True)
	title = models.CharField(max_length=500)
	category = models.ForeignKey(ServiceCategory, blank=True, on_delete=models.CASCADE)
	service = models.ForeignKey(Service, on_delete=models.CASCADE)
	#When the project is completed and payment made, then this is turned to True
	completed = models.BooleanField(default=False)
	description = models.TextField()
	image = models.ImageField(blank=True)
	other_information = models.TextField(blank=True)

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('home:postedproject', args=[self.id])


#Service providers adding sample to their dashboard for display
class SampleServiceDisplay(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	servicecategory = models.ForeignKey(ServiceCategory, on_delete=models.CASCADE)
	service = models.ForeignKey(Service, on_delete=models.CASCADE)
	search_tags = models.CharField(max_length=500, blank=True)
	description = models.TextField()
	sample_image = models.ImageField(blank=True)

	def __str__(self):
		return self.service.name

	@property
	def service_name(self):
		return self.service.name
	
	@property
	def user_name(self):
		return self.user.username

	def get_absolute_url(self):
		return reverse('home:postedsample', args=[self.id, self.slug])

#For placing bids on available projects
class ProjectBid(models.Model):
	date_created = models.DateTimeField(auto_now_add=True)
	project = models.ForeignKey(PostProject, on_delete=models.CASCADE)
	bidder = models.ForeignKey(ServiceProvider, related_name='bidding_provider', on_delete=models.CASCADE)
	client = models.ForeignKey(User, related_name='project_owner', on_delete=models.CASCADE)
	service = models.ForeignKey(Service, related_name='project_service', on_delete=models.CASCADE)
	#slug = models.SlugField()
	cost = models.DecimalField(max_digits=10, decimal_places=2)
	commission = models.DecimalField(max_digits=10, decimal_places=2)
	bid_reference = models.CharField(max_length=50)
	total_cost = models.DecimalField(max_digits=10, decimal_places=2)
	description = models.TextField(blank=True)

	def __str__(self):
		return self.project.title 

	def get_absolute_url(self):
		return reverse('home:projectbids', args=[self.project.id])


class VendorSample(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	description = models.TextField()
	image = models.ImageField(blank=True, null=True)

	def __str__(self):
		return self.user.username 

	


class ServiceRequest(models.Model):
	date_created = models.DateTimeField(auto_now_add=True)
	service = models.ForeignKey(Service, on_delete=models.CASCADE)
	# client = models.ForeignKey(User, on_delete=models.PROTECT),
	vendor = models.ForeignKey(User, related_name="provider", on_delete=models.CASCADE)
	service_user = models.ForeignKey(User, related_name="client_user", on_delete=models.CASCADE) # Due to django's mood-swings, I used this for clients
	delivery = models.BooleanField(default=True)   # This is true cos we will be doing delivery for items
	delivery_duration = models.CharField(max_length=200, null=True, blank=True)  # For vendor to let the client know when the service will be ready 
	cost = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True) #Vendor's total charge
	service_fee = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True) # Percentage of vendor's charge
	delivery_fee = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)  # Delivery charge
	total_cost = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)  # Vendor's charge + service_fee + delivery
	client_confirmation = models.BooleanField(default=False)   # For client to confirm acceptance of fee 
	payment_made = models.BooleanField(default=False)   #  This will check payment model if payment is made, once made, set to True and send to client to begin production
	service_dispatched = models.BooleanField(default=False)  # For vendor to notify the client when item is en route to e delivered

home/templates/home/posted_projects.html
{% extends 'home/basic.html' %}


{% block body %}
<div class="container">
    {% for name in sampleservicedisplay_list %}
        <p>{{ name.service }}</p>
        <p>{{ name.servicecategory }}</p>
    {% endfor %}
</div>


{% endblock %}

home/templates/home/postproject.html
{% extends 'home/basic.html' %}

{% block css %}
<style>
    #id_client{display: none;}
</style>
{% endblock %}

{% block body %}
{% load static %}
{% load widget_tweaks %}

<div class="col-12 col-md-3 col-2 bd-sidebar">
      <a href="{% url 'home:profile' %}">Go to your dashboard</a>
</div>


<div class="container">
    <div class="header mx-auto" style="width: 400px;">
        <p style="float: left">Post your request for a service here</p>
    </div>
    
    <form method="post" class="mx-auto" enctype="multipart/form-data">
        {% csrf_token %}
        
		<div class="form-group row">
            <!--label for="colFormLabel" class="col-sm-2 col-form-label">Client</label-->
            <div class="col-sm-10">
                {{ postproject_form.client | add_class:"css_class" | attr:"placeholder:Client" }}
            </div>
        </div>
        <div class="form-group row">
            <label for="colFormLabel" class="col-sm-2 col-form-label">Title</label>
            <div class="col-sm-10">
                {{ postproject_form.title | add_class:"css_class" | attr:"placeholder:Title" }}
            </div>
        </div>
        <div class="form-group row">
            <label for="colFormLabel" class="col-sm-2 col-form-label">Category</label>
            <div class="col-sm-10">
                {{ postproject_form.category | add_class:"css_class" | attr:"placeholder:Category" }}
            </div>
        </div>
        
        <div class="form-group row">
            <label for="colFormLabel" class="col-sm-2 col-form-label">Service</label>
            <div class="col-sm-10">
                {{ postproject_form.service | add_class:"css_class" | attr:"placeholder:Service" }}
            </div>
        </div>
        <div class="form-group row">
            <label for="colFormLabel" class="col-sm-2 col-form-label">Description</label>
            <div class="col-sm-10">
                {{ postproject_form.description | add_class:"css_class" | attr:"placeholder:Description" }}
            </div>
        </div>
        <div class="form-group row">
            <label for="colFormLabel" class="col-sm-2 col-form-label">Other Information</label>
            <div class="col-sm-10">
                {{ postproject_form.other_information | add_class:"css_class" | attr:"placeholder:Other Information" }}
            </div>
        </div>
        
        <div class="form-group row">
            <label for="colFormLabel" class="col-sm-2 col-form-label">Image</label>
            <div class="col-sm-10">
                If you wish to add an image, please upload it here
                {{ postproject_form.image | add_class:"css_class" | attr:"placeholder:Image" }}
            </div>
        </div>
                
      
        <div class="col-sm-12 mx-auto" style="width: 50px; margin-bottom: 50px;">
            <div class="col-md-12">
                <hr>
                <div class="card-actionbar-row">
                    <input type="submit" class="btn btn-flat btn-lg btn-primary ink-reaction" value="SUBMIT">
                </div>
            </div>
        </div>
        
        
    </form>
  
    
</div>








<!--div class="container">
    <form method="post">
        {% csrf_token %}
        {{ postproject_form.as_p }}
        <input type="submit" value="Submit">
    </form>
</div-->

<!--Remember to implement the dependent dropdown here too-->

{% endblock %}

home/templates/home/project_list.html
{% extends 'home/basic.html' %}

{% block body %}
{% load static %}
{% load widget_tweaks %}


<div class="col-12 col-md-3 col-2 bd-sidebar">
      <a href="{% url 'home:profile' %}">Go to your dashboard</a>
</div>

<div class="container" style="margin: 20px 50px;">
    <div class="row">
        {% for name in my_user %}
        <div class="col-sm-6 col-sm-3">
            <a href="{% url 'home:postedproject' name.id %}">
                {% if name.image %}
                    <img src="{{ name.image.url }}" style="width: 250px; height: 250px;">
                {% else %}
                    <img src="{% static 'home/no_image.png' %}" style="width: 250px; height: 250px;">
                {% endif %}
                <p>{{ name.title }}</p>
                <p>{{ name.service }}</p>
            </a>
        </div>
     {% endfor  %}
    </div>
</div>







{% endblock %}

home/templates/home/sample_display_detail.html
{% extends 'home/basic.html' %}


{% block body %}




<div class="container">
    <div class="row">
        <div class="col-sm-12 col-sm-3">
            <img src="{{ servicesample.sample_image.url }}" style="width: 900px; height: 350px">
        </div>
        <div class="col-sm-6 col-sm-3">
            <p>{{ servicesample.service }}</p>
            <p>{{ servicesample.servicecategory }}</p>
            <p>{{ servicesample.description }}</p>
        </div>
    </div>
</div>


{% endblock %}

home/templates/home/search_results.html
{% extends 'home/basic.html' %}

{% block body %}
{% load static %}
{% load widget_tweaks %}



<div class="container">
    <div class="row">
        <div class="col">
            {% for result in results %}
            <li>{{ result }}</li>
            {% endfor %}
        </div>
    </div>

</div>





















{% endblock %}

home/templates/home/serv_category.html
{% extends 'home/basic.html' %}


{% block body %}
{% load static %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}




<div class="container text-uppercase font-weight-bold">
    <p>{{ slug }}</p>
</div>


<div class="col-12 col-md-3 col-2 bd-sidebar">
      <a href="{% url 'home:profile' %}">Go to your dashboard</a>
</div>


<div class="container">    
    <div class="row">
        {% for objects in sercatlist %}
        <div class="border border-light col-6 col-sm-3" style="margin: 10px 5px 10px 15px;">
            <a href="{% url 'home:service_result_page' objects.slug %}"><img style="width: 240px; height: 200px" src="{{ objects.sample_image.url }}" class="circle img-fluid" onerror="this.src='{% static 'home/no_image.png' %}'"></a>
            
            <p>{{ objects.name }}</p>
    </div>
      {% endfor %}
   
</div>

{% endblock %}

home/templates/home/service_page.html
{% extends 'home/basic.html' %}


{% block body %}
{% load static %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}


<div class="col-12 col-md-3 col-2 bd-sidebar">
      <a href="{% url 'home:profile' %}">Go to your dashboard</a>
</div>


{% if not servicepage %}
<div class="container">
    
    <p>No service providers registered under this category</p>
</div>
{% else %}
<div class="container align-self-center">
    
    <p>List of service Providers and their portfolios under <i class="text-uppercase font-weight-bold">{{ slug }}</i></p>
</div>

<!--Search results will go here-->
<div class="col-12 col-md-3 col-2 bd-sidebar">
    <p>Hey</p>
</div>
<!--End of the search results-->

<!--Display of the services in a grid layout-->
<div class="container">    
    <div class="row">
        {% for sampserv in servicepage %}
        <div class="border border-light col-6 col-md-3" style="margin: 10px 5px 10px 15px;">
            <a href="{% url 'home:userdashboard' sampserv.user.id %}"><img src="{{ sampserv.sample_image.url }}" class="img-thumbnal img-fluid" ></a>
            <p>Category: {{ sampserv.servicecategory.name }}</p>
            <p>{{ sampserv.service.name }}</p>
            <p>{{ sampserv.user.username }}</p>
    </div>
      {% endfor %}
   
</div>

{% endif %}
<!--End of the display of the services-->



{% endblock %} 

home/templates/home/view_profile.html
{% extends 'home/basic.html' %}
{% load crispy_forms_tags %}

{% block css %}
<style>
    #message{display: none}
	#review{display: none}
	#projects{display: none}
</style>
{% endblock %}

{% block body %}
{% load static %}

<div class="container" style="margin: 30px 40px 20px;" >
    
    <div class="row">
        <div class="col-xs-6" style="margin-right: 30px;">
            {% if up.profile_picture %}
                <img src="{{ up.profile_picture.url }}" class="userprofile img-responsive" style="border-radius: 50%; width: 122px; height: 122px;" onerror="{% static 'home/no_image.png' %}">
            {% else %}
                <img src="{% static 'home/no_image.png' %}" class="userprofile img-responsive" style="border-radius: 50%; width: 122px; height: 122px;">
            {% endif %}
        </div>
        <div class="col-xs-6" style="margin-right: 30px;">
            <p>{{ user.first_name }} {{ user.last_name }}</p>
            <p>EMAIL: {{ user.email }}</p>
            <p>Contact: {{ up.phone_number }}</p>
            <p>{{ up.occupation }} @ {{ up.organization }}</p>
            
        </div>
        <div class="col-xs-6" style="margin-right: 60px;">
           <a href="{% url 'home:edit_profile' %}">Edit Profile</a><span class="glyphicon glyphicon-pencil"></span>
		   
        </div>
		<div class="col-xs-6" style="margin-right: 60px;">
			<a href="{% url 'home:service_registration' %}">Register for a service</a><span class="glyphicon glyphicon-pencil"></span>
        </div>
    </div>
</div>


<div class="container">
    <div class="row user_profile_navbar" style="background-color: #2c2c54;">
        <div class="col-sm-3">
            <a href="javascript:void(0)" onclick="sampleToggle()"><div class="header" style="background-color: #d1ccc0;">Sample</div></a>            
        </div>
        <div class="col-sm-3">
            <a href="javasscript:void(0)" onclick="messageToggle()"><div class="header" style="background-color: #2c2c54;">Messages</div></a>
        </div>
        <div class="col-sm-3">
            <a href="javascript:void(0)" onclick="projectsToggle()"><div class="header" style="background-color: #2c2c54;">Your projects</div></a>
        </div>
        <div class="col-sm-3">
            <a href="javascript:void(0)" onclick="reviewToggle()"><div class="header" style="background-color: #2c2c54;">Reviews</div></a>
        </div>
    </div>
    <div class="row" id="sample">
        <div class="col-xs-6 sample" style="margin-right: 30px; overflow-x: hidden">
            <div class="row sample">
                {% if sampleprojs %}
                {% for projs in sampleprojs %}
                    {% if projs.sample_image %}
                <a href="{% url 'home:postedsample' projs.id %}">
                    <img src="{{ projs.sample_image.url }}" class="img-responsive" style="border-radius: 50%; width: 220px; height: 220px; margin: 15px 25px 15px" onerror="{% static 'home/no_image.png' %}">
                    {% else %}
                    <img src="{% static 'home/no_image.png' %}" class="img-responsive" style="border-radius: 50%; width: 220px; height: 220px;">
                    {% endif %}
                    <p style="margin: 15px 15px 15px; left: 50%">{{ projs }}</p>
                    <p style="margin: 15px 15px 15px; left: 50%">{{ projs.description }}</p>
                </a>
                {% endfor %}
                {% endif %}
                
            </div>
            <p><a href="{% url 'home:sample_project_display' %}" >Click here </a>to post some of your work to help potential clients find you easily</p>            
        </div>
            
    </div>
    <div class="row" id="message">
        {% if mesages %}
                <div class="" id="" style="display: block">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Receipient</th>
                                <th>Message</th>
                                <th>Date Created</th>
                            </tr>
                        </thead>
                        {% for projs in mesages %}
                        <tr>
                            {% if projs.fromUser == request.user %}
                            <td><a href="javascript:void(0)" onclick="toggleMessageDetail()">{{ projs.toUser }}</a></td>
                            {% else %}
                            <td><a href="javascript:void(0)" onclick="toggleMessageDetail()">{{ projs.fromUser }}</a></td>
                        {% endif %}
                            <td>{{ projs.message }}</td>
                            <td>{{ projs.createdAt }} </td>
                        </tr>
                    {% endfor %}
                    </table>
                </div>
		{% else %}
            <p>You have no messages at this time</p>
            
        {% endif %}
            
    </div>
	
	<div class="row" id="review">
        {% if client_review %}
                <div class="" id="" style="display: block">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Client</th>
                                <th>Transaction ID</th>
                                <th>Review</th>
                            </tr>
                        </thead>
                        {% for projs in client_review %}
                        <tr class="">
                            <td> {{ projs.user }}</td>                        
                            <td>{{ projs.transaction_id }}</td>
                            <td>{{ projs.review }} </td>
                        </tr>
                    {% endfor %}
                        <tr></tr>
                    </table>
                </div>
        {% else %}
            <p>You have no reviews at this time. After you have completed a work, then your client can post a review about the work.</p>
        {% endif %}
            
    </div>
	<div class="row" id="projects">
        {% if user_projects %}
                <div class="" id="" style="display: block">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Title</th>
                                <th>Name</th>
                                <th>Description</th>
                                <th>Image</th>
                            </tr>
                        </thead>
                        {% for projs in user_projects %}
                        <tr class="">
                            <td><a href="#"> {{ projs.title }}</a></td>                        
                            <td>{{ projs.service }}</td>
                            <td>{{ projs.description }} </td>
                            {% if projs.image %}
                            <td><img src="{{ projs.image.url }}" height="100px" width="100px"></td>
                            {% else %}
                            <td><img src="{% static 'home/no_image.png' %}" width="100px" height="100px"></td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                        <tr></tr>
                    </table>
                </div>
        {% else %}
            <p>You have not posted any work to be done for you yet. You can always post a project and get in touch with service providers</p>
        {% endif %}
            
    </div>
    
</div>





<script>
   
   function messageToggle() {
        document.getElementById('sample').style.display = 'none';
        document.getElementById('message').style.display = 'block';
        document.getElementById('review').style.display = 'none';
        document.getElementById('projects').style.display = 'none';
    }
    
    function sampleToggle() {
        document.getElementById('sample').style.display = 'block';
        document.getElementById('message').style.display = 'none';
        document.getElementById('review').style.display = 'none';
        document.getElementById('projects').style.display = 'none';
    }
    
    function projectsToggle() {
        document.getElementById('sample').style.display = 'none';
        document.getElementById('message').style.display = 'none';
        document.getElementById('review').style.display = 'none';
        document.getElementById('projects').style.display = 'block';
    }
    
    function reviewToggle() {
        document.getElementById('sample').style.display = 'none';
        document.getElementById('message').style.display = 'none';
        document.getElementById('review').style.display = 'block';
        document.getElementById('projects').style.display = 'none';
    }


</script>
        
<!--
        {% for msg in mesages %}
                {% if msg.fromUser == request.user %}
                    {{ msg.toUser }}
                {% else %}
                    {{ msg.fromUser }}
                {% endif %}
                {% endfor %}
 -->


{% endblock %}